management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
    java:
      enabled: true
    env:
      enabled: true


  cus-log:
    properties:
      max-limit: 1024
      plain-markers: "PLAIN1,PLAIN2"
      # get ss007 and 123 from {"username": "ss007","password": "123"}
      regex: ((?<="username":\s*").*?(?=")|(?<="password":\s*").*?(?="))






