spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: 10s
#    cluster:
#      nodes:
#        - 172.19.0.11:6379
#        - 172.19.0.12:6380
#        - 172.19.0.13:6381
#        - 172.19.0.14:6382
#        - 172.19.0.15:6383
#        - 172.19.0.16:6384
#      max-redirects: 3



